version: "3.9"
services:
  registry:
    build: ./registry
    ports:
      - "8080:8080"
  broker:
    build: ./broker
    ports:
      - "80:80"
    depends_on:
      - "registry"
  com-0:
    build: ./com-0
    ports:
      - "4567:4567"
    depends_on:
      - "broker"
  com-1:
    build: ./com-1
    ports:
      - "5372:5372"
    depends_on:
      - "broker"