version: "2.2"
services:
  server3: 
    image: server3
    container_name: server3
    ports : 
      - 3003:3003
  server4: 
    image: server4
    container_name: server4
    ports : 
      - 3004:3004
    depends_on: 
      - server3
  server2: 
    image: server2
    container_name: server2
    ports : 
      - 3002:3002
    depends_on: 
      - server3
  server1: 
    image: server1
    container_name: server1
    ports : 
      - 3001:3001
    depends_on: 
      - server3
